server:
  port: 8762
spring:
  application:
    name: config-singe-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sy831529/take-out-config.git
          default-label: master
          search-paths: config
          username:
          password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/